title: Data Science Pedagogy Workshop
logo: /img/logo.png
description: This is hands-on workshop for current and future educators of underrepresented and underserved students in Data Science and Machine Learning. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
